/**
 * B-Attend Excel XLSX Export Utility
 *
 * Uses ExcelJS to generate real .xlsx files (not renamed CSV).
 * Supports: styled headers, frozen header row, auto-width columns,
 * summary sheet, multiple sheets, filters, date/number formatting,
 * RTL support for Arabic, UTF-8 Arabic names.
 */

import ExcelJS from "exceljs";
import { NextResponse } from "next/server";

export interface ExcelColumn {
  key: string;
  label: string;
  width?: number;
  format?: string;
}

export interface ExcelRow {
  [key: string]: string | number | Date | null | undefined;
}

export interface ReportHeaderInfo {
  companyName: string;
  reportTitle: string;
  generatedBy: string;
  generatedAt: Date;
  filters?: Record<string, string | undefined>;
  planNote?: string;
}

/**
 * Create a new Excel workbook.
 */
export function createWorkbook(): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = "B-Attend SaaS";
  wb.created = new Date();
  return wb;
}

/**
 * Add a summary/header sheet with company name, report title, filters, timestamp.
 */
export function addReportHeaderSheet(wb: ExcelJS.Workbook, info: ReportHeaderInfo): ExcelJS.Worksheet {
  const ws = wb.addWorksheet("Summary", { views: [{ rightToLeft: false }] });

  // Title
  ws.getCell("A1").value = info.companyName;
  ws.getCell("A1").font = { size: 16, bold: true, color: { argb: "FF0B2545" } };
  ws.getCell("A2").value = info.reportTitle;
  ws.getCell("A2").font = { size: 14, bold: true, color: { argb: "FF1E88E5" } };

  // Metadata
  ws.getCell("A4").value = "Generated by:";
  ws.getCell("B4").value = info.generatedBy;
  ws.getCell("A5").value = "Generated at:";
  ws.getCell("B5").value = info.generatedAt.toLocaleString();
  ws.getCell("B5").numFmt = "yyyy-mm-dd hh:mm:ss";

  // Filters
  let row = 7;
  if (info.filters && Object.keys(info.filters).length > 0) {
    ws.getCell(`A${row}`).value = "Active Filters";
    ws.getCell(`A${row}`).font = { bold: true, size: 12 };
    row++;
    for (const [k, v] of Object.entries(info.filters)) {
      if (v) {
        ws.getCell(`A${row}`).value = k;
        ws.getCell(`B${row}`).value = v;
        row++;
      }
    }
    row++;
  }

  if (info.planNote) {
    ws.getCell(`A${row}`).value = "Plan Note";
    ws.getCell(`A${row}`).font = { bold: true };
    ws.getCell(`B${row}`).value = info.planNote;
    row += 2;
  }

  // Privacy note
  ws.getCell(`A${row}`).value = "This report is generated from B-Attend SaaS. Data is tenant-scoped and confidential.";
  ws.getCell(`A${row}`).font = { italic: true, size: 9, color: { argb: "FF64748B" } };

  // Column widths
  ws.columns = [
    { width: 22 },
    { width: 40 },
  ];

  return ws;
}

/**
 * Format the header row of a worksheet: bold, colored background, frozen.
 */
export function formatHeaderRow(ws: ExcelJS.Worksheet, columns: ExcelColumn[]): void {
  const headerRow = ws.getRow(1);
  headerRow.height = 22;
  columns.forEach((col, i) => {
    const cell = headerRow.getCell(i + 1);
    cell.value = col.label;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 11 };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF0B2545" },
    };
    cell.alignment = { vertical: "middle", horizontal: "left" };
    cell.border = {
      bottom: { style: "thin", color: { argb: "FF1E88E5" } },
    };
  });
  headerRow.commit();

  // Freeze the header row
  ws.views = [{ state: "frozen", ySplit: 1 }];

  // Enable auto-filter
  ws.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: columns.length },
  };
}

/**
 * Auto-fit column widths based on content.
 */
export function autoFitColumns(ws: ExcelJS.Worksheet, columns: ExcelColumn[], rows: ExcelRow[]): void {
  columns.forEach((col, colIdx) => {
    let maxLen = col.label.length;
    for (const row of rows) {
      const val = row[col.key];
      if (val !== null && val !== undefined) {
        const strVal = val instanceof Date ? val.toLocaleDateString() : String(val);
        maxLen = Math.max(maxLen, strVal.length);
      }
    }
    // Set width with padding, clamped between 10 and 50
    ws.getColumn(colIdx + 1).width = col.width ?? Math.min(Math.max(maxLen + 3, 10), 50);
  });
}

/**
 * Add a worksheet from rows + columns.
 */
export function addWorksheetFromRows(
  wb: ExcelJS.Workbook,
  sheetName: string,
  columns: ExcelColumn[],
  rows: ExcelRow[],
  options: { rtl?: boolean } = {},
): ExcelJS.Worksheet {
  const ws = wb.addWorksheet(sheetName, {
    views: [{ rightToLeft: options.rtl ?? false, state: "frozen", ySplit: 1 }],
  });

  // Format header
  formatHeaderRow(ws, columns);

  // Add data rows
  rows.forEach((row, rowIdx) => {
    const excelRow = ws.getRow(rowIdx + 2);
    columns.forEach((col, colIdx) => {
      const cell = excelRow.getCell(colIdx + 1);
      const val = row[col.key];
      cell.value = safeExcelValue(val);
      if (col.format) cell.numFmt = col.format;
      // Alternating row color
      if (rowIdx % 2 === 1) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF8FAFC" } };
      }
    });
    excelRow.commit();
  });

  // Auto-fit columns
  autoFitColumns(ws, columns, rows);

  return ws;
}

/**
 * Apply RTL (right-to-left) layout to a worksheet — for Arabic-friendly exports.
 */
export function applyRTLIfNeeded(ws: ExcelJS.Worksheet, rtl: boolean): void {
  if (rtl) {
    ws.views = ws.views || [];
    (ws.views[0] as any) = { ...(ws.views[0] as any), rightToLeft: true };
  }
}

/**
 * Send workbook as HTTP response with proper headers.
 */
export async function sendWorkbookResponse(wb: ExcelJS.Workbook, filename: string): Promise<NextResponse> {
  const buffer = await wb.xlsx.writeBuffer();
  return new NextResponse(buffer, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}

/**
 * Format minutes as hours string (e.g. 480 → "8.00h").
 */
export function formatMinutesAsHours(minutes: number): string {
  return `${(minutes / 60).toFixed(2)}h`;
}

/**
 * Safely convert any value to an Excel-compatible value.
 * Handles null, undefined, Date, boolean, etc.
 */
export function safeExcelValue(val: unknown): string | number | Date | null {
  if (val === null || val === undefined) return null;
  if (val instanceof Date) return val;
  if (typeof val === "boolean") return val ? "Yes" : "No";
  if (typeof val === "number") return val;
  if (typeof val === "string") return val;
  return String(val);
}

/**
 * Generate a filename with date suffix.
 */
export function excelFilename(prefix: string, dateStr?: string): string {
  const d = dateStr ?? new Date().toISOString().split("T")[0];
  return `${prefix}-${d}.xlsx`;
}
